import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/navigation/mobile/Header";
import MobileNavigation from "@/components/navigation/mobile/MobileNavigation";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-screen flex flex-col bg-page text-light ${inter.className}`}
      >
        <Header />
        <main className="pb-20">{children}</main>
        <MobileNavigation />
      </body>
    </html>
  );
}
